//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EngineResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EngineResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.EngineResource", typeof(EngineResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine run error message =.
        /// </summary>
        internal static string EngineErrorMessagePrefix {
            get {
                return ResourceManager.GetString("EngineErrorMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage : Engine.exe \&quot;the path of test json file\&quot; ...
        ///        You may input multiple test json files
        ///        For example: Engine.exe .\\files\\test1.json .\\files\\test2.json.
        /// </summary>
        internal static string EngineMessage {
            get {
                return ResourceManager.GetString("EngineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to close test process..
        /// </summary>
        internal static string FailClosePrefix {
            get {
                return ResourceManager.GetString("FailClosePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; doesn&apos;t exist..
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final test result is FAILED!.
        /// </summary>
        internal static string FinalResultFailed {
            get {
                return ResourceManager.GetString("FinalResultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final test result is PASS!.
        /// </summary>
        internal static string FinalResultPass {
            get {
                return ResourceManager.GetString("FinalResultPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input file. Engine stops..
        /// </summary>
        internal static string NoInputFile {
            get {
                return ResourceManager.GetString("NoInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; test doesn&apos;t contain any test step..
        /// </summary>
        internal static string NoTestStep {
            get {
                return ResourceManager.GetString("NoTestStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is done. The result is {1}..
        /// </summary>
        internal static string RunTestFinalMessage {
            get {
                return ResourceManager.GetString("RunTestFinalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running end-to-end test - {0}.
        /// </summary>
        internal static string RunTestHeaderMessage {
            get {
                return ResourceManager.GetString("RunTestHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program to test ({0}) is closed..
        /// </summary>
        internal static string TestProgramClosed {
            get {
                return ResourceManager.GetString("TestProgramClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program to test ({0}) fails to launch..
        /// </summary>
        internal static string TestProgramFailedLaunch {
            get {
                return ResourceManager.GetString("TestProgramFailedLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program to test ({0}) is launched..
        /// </summary>
        internal static string TestProgramLaunched {
            get {
                return ResourceManager.GetString("TestProgramLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This test has {0} test step(s)..
        /// </summary>
        internal static string TestStepCountMessage {
            get {
                return ResourceManager.GetString("TestStepCountMessage", resourceCulture);
            }
        }
    }
}
