//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2020.ImageServiceProxy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P2020.ImageServiceProxy.ServiceResource", typeof(ServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json result is empty from Azure OCR service. Azure OCR failed!.
        /// </summary>
        internal static string AzureEmtpyOCRResult {
            get {
                return ResourceManager.GetString("AzureEmtpyOCRResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureOCRService GetOCRJsonResultAsync() error..
        /// </summary>
        internal static string AzureOCRGeneralError {
            get {
                return ResourceManager.GetString("AzureOCRGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file or search text is empty!.
        /// </summary>
        internal static string EmptyImageFileSearchText {
            get {
                return ResourceManager.GetString("EmptyImageFileSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file does not exist in file system!.
        /// </summary>
        internal static string ImageFileNotExist {
            get {
                return ResourceManager.GetString("ImageFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error on http request..
        /// </summary>
        internal static string NetworkErrorOnHttpRequest {
            get {
                return ResourceManager.GetString("NetworkErrorOnHttpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find text &quot;{0}&quot; in json result at {1}. Json file = {2}..
        /// </summary>
        internal static string TextNotFoundInJsonResult {
            get {
                return ResourceManager.GetString("TextNotFoundInJsonResult", resourceCulture);
            }
        }
    }
}
